// Deterministic seed data for the B4F Hub local API.
// Restarting the server resets everything back to this exact state — this is
// intentional, so the assessment is reproducible for every student and for
// re-grading.

export const initialPosts = [
  {
    id: 1,
    author: "Mona Al-Sayed",
    avatar: "MA",
    category: "announcement",
    content:
      "Cohort 8's Demo Day is confirmed for the last Thursday of this month! Alumni, trainers, and hiring partners are all invited. Details + RSVP link coming next week.",
    createdAt: "2026-08-20T09:00:00.000Z",
    likes: 24,
    liked: false,
  },
  {
    id: 2,
    author: "Youssef Nabil",
    avatar: "YN",
    category: "event",
    content:
      "Hosting a free weekend workshop on Git branching strategies for anyone who wants a refresher before their team project. Saturday, 10am, Room B.",
    createdAt: "2026-08-19T14:30:00.000Z",
    likes: 15,
    liked: false,
  },
  {
    id: 3,
    author: "Farida Hossam",
    avatar: "FH",
    category: "community",
    content:
      "Huge thanks to everyone who showed up to yesterday's mock interview night. Got three separate pieces of feedback that genuinely changed how I answer 'tell me about a bug you fixed.'",
    createdAt: "2026-08-19T08:15:00.000Z",
    likes: 41,
    liked: true,
  },
  {
    id: 4,
    author: "Karim El-Sherif",
    avatar: "KE",
    category: "resource",
    content:
      "Sharing my personal notes on React state vs. derived data — the exact distinction that took me three sessions to actually internalize. Link in the comments (ask me directly, no comment API yet!).",
    createdAt: "2026-08-18T19:45:00.000Z",
    likes: 33,
    liked: false,
  },
  {
    id: 5,
    author: "Nourhan Adel",
    avatar: "NA",
    category: "community",
    content:
      "Anyone else's brain completely melt during the Stack vs Queue lecture and then suddenly click two days later? Just me? Okay.",
    createdAt: "2026-08-18T11:00:00.000Z",
    likes: 52,
    liked: false,
  },
  {
    id: 6,
    author: "Tamer Fathy",
    avatar: "TF",
    category: "announcement",
    content:
      "Program coordinators: the alumni mentorship sign-up sheet closes this Friday at midnight. If you haven't matched a mentee yet, now's the time.",
    createdAt: "2026-08-17T10:00:00.000Z",
    likes: 18,
    liked: false,
  },
  {
    id: 7,
    author: "Salma Ibrahim",
    avatar: "SI",
    category: "resource",
    content:
      "Compiled a short list of every free API we used across the course (JSONPlaceholder and friends) in case anyone wants to keep practicing after graduation.",
    createdAt: "2026-08-16T16:20:00.000Z",
    likes: 29,
    liked: true,
  },
  {
    id: 8,
    author: "Ahmed Zaki",
    avatar: "AZ",
    category: "event",
    content:
      "Cohort 7 alumni panel this Wednesday evening — three people who got hired in the last six months talking honestly about the job search. Open to all cohorts.",
    createdAt: "2026-08-16T08:00:00.000Z",
    likes: 37,
    liked: false,
  },
  {
    id: 9,
    author: "Dina Wagdy",
    avatar: "DW",
    category: "community",
    content:
      "Small win: finally got my TypeScript build to pass with zero `any` types anywhere in the project. Felt disproportionately good.",
    createdAt: "2026-08-15T20:10:00.000Z",
    likes: 46,
    liked: false,
  },
  {
    id: 10,
    author: "Hany Mostafa",
    avatar: "HM",
    category: "resource",
    content:
      "If anyone's stuck on immutable array updates: the mental model that finally worked for me was 'never edit, always rebuild.' Happy to pair for 20 minutes if that helps.",
    createdAt: "2026-08-15T09:30:00.000Z",
    likes: 22,
    liked: false,
  },
  {
    id: 11,
    author: "Rania Kamal",
    avatar: "RK",
    category: "announcement",
    content:
      "The program office moved the final project deadline extension request form — it's now under Resources, not Announcements. Sorry for the confusion!",
    createdAt: "2026-08-14T13:00:00.000Z",
    likes: 9,
    liked: false,
  },
  {
    id: 12,
    author: "Omar Reda",
    avatar: "OR",
    category: "community",
    content:
      "Genuinely one of the best parts of this program has been how many of you actually answer questions in the group chat at 11pm without being asked twice. Real community, not just a class.",
    createdAt: "2026-08-13T22:40:00.000Z",
    likes: 63,
    liked: false,
  },
  {
    id: 13,
    author: "Nadine Sabry",
    avatar: "NS",
    category: "event",
    content:
      "Reminder: the CV clinic with career services is drop-in, no booking needed. Bring a laptop and a rough draft, leave with something you can actually send.",
    createdAt: "2026-08-12T15:00:00.000Z",
    likes: 12,
    liked: false,
  },
  {
    id: 14,
    author: "Sherif Adly",
    avatar: "SA",
    category: "resource",
    content:
      "Longer post, apologies in advance: I want to write down the full story of how I debugged a state-update-ordering bug that took me four hours, because I think the underlying lesson generalizes past this one bug. The short version is that I was calling setState twice in the same handler, each one built from the same stale snapshot of the array, so the second call silently overwrote whatever the first one changed — the fix was combining both changes into one object before calling the setter a single time, which is exactly the 'one callback, one commit' pattern from Session 11. The longer version is that I didn't actually understand WHY this happened until I read through how React batches updates and realized that neither of my two calls ever saw the other's result — they were both working from the same closure. If you're hitting a bug where 'half my update disappears' or 'only one of the two fields I changed actually saved', check for this exact pattern first. It cost me an afternoon so hopefully it costs you five minutes instead.",
    createdAt: "2026-08-11T18:25:00.000Z",
    likes: 71,
    liked: true,
  },
  {
    id: 15,
    author: "Yasmin Talaat",
    avatar: "YT",
    category: "community",
    content:
      "Is anyone else's favorite part of TaskFlow the fact that it quietly became the app none of us can stop mentally redesigning even outside of class?",
    createdAt: "2026-08-11T09:10:00.000Z",
    likes: 27,
    liked: false,
  },
  {
    id: 16,
    author: "Mahmoud Fouad",
    avatar: "MF",
    category: "announcement",
    content:
      "New: a #hiring-leads channel has been added to the alumni Slack. Please only post roles you've personally verified are real and currently open.",
    createdAt: "2026-08-10T11:45:00.000Z",
    likes: 19,
    liked: false,
  },
  {
    id: 17,
    author: "Heba Younes",
    avatar: "HY",
    category: "event",
    content:
      "Running an informal 'explain your project to a 10-year-old' lightning round after class tomorrow. It's a surprisingly good way to find the actual holes in your own understanding.",
    createdAt: "2026-08-09T17:30:00.000Z",
    likes: 34,
    liked: false,
  },
  {
    id: 18,
    author: "Bassem Anwar",
    avatar: "BA",
    category: "resource",
    content:
      "Put together a one-page cheat sheet comparing Stack, Queue, Hash Table, and Hash Set — when each one is actually the right tool, not just the definitions. Ping me if you want it.",
    createdAt: "2026-08-08T12:00:00.000Z",
    likes: 58,
    liked: false,
  },
];

export const initialOpportunities = [
  {
    id: 101,
    title: "Junior Frontend Developer",
    company: "NovaWorks",
    companyLogo: "NW",
    type: "job",
    workMode: "hybrid",
    location: "Cairo, Egypt",
    skills: ["React", "TypeScript", "CSS", "Git"],
    description:
      "NovaWorks is looking for a junior frontend developer to join our small product team. You'll work directly with two senior engineers on a real customer-facing dashboard, with plenty of code review and mentorship built into the role.",
    deadline: "2026-09-30",
    postedAt: "2026-08-15",
    level: "junior",
    applied: false,
  },
  {
    id: 102,
    title: "Frontend Engineering Internship",
    company: "BrightPath Analytics",
    companyLogo: "BP",
    type: "internship",
    workMode: "remote",
    location: "Remote (MENA)",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    description:
      "A 3-month paid internship building internal tooling used by our own data team. Great fit for someone who just finished a bootcamp and wants real production experience before their first full-time role.",
    deadline: "2026-09-15",
    postedAt: "2026-08-20",
    level: "entry",
    applied: false,
  },
  {
    id: 103,
    title: "Full-Stack Developer",
    company: "Cedar Robotics",
    companyLogo: "CR",
    type: "job",
    workMode: "on-site",
    location: "Giza, Egypt",
    skills: ["React", "Node.js", "Express", "TypeScript", "PostgreSQL"],
    description:
      "Cedar Robotics builds fleet-management software for industrial robots. We need a full-stack developer comfortable moving between a React frontend and a Node/Express API, with an appetite for learning basic robotics domain concepts on the job.",
    deadline: "2026-10-05",
    postedAt: "2026-08-12",
    level: "mid",
    applied: false,
  },
  {
    id: 104,
    title: "Data Analyst Scholarship — 2026 Cohort",
    company: "Delta Health Solutions",
    companyLogo: "DH",
    type: "scholarship",
    workMode: "hybrid",
    location: "Cairo, Egypt",
    skills: ["Excel", "SQL", "Data Visualization"],
    description:
      "A fully-funded 6-week scholarship program covering healthcare data analysis fundamentals, ending in a guaranteed interview for an analyst role. Open to recent graduates from any technical bootcamp.",
    deadline: "2026-09-25",
    postedAt: "2026-08-10",
    level: "entry",
    applied: false,
  },
  {
    id: 105,
    title: "Community Tech Volunteer",
    company: "Nile Youth Foundation",
    companyLogo: "NY",
    type: "volunteer",
    workMode: "on-site",
    location: "Alexandria, Egypt",
    skills: ["HTML", "CSS", "Teaching"],
    description:
      "Help run weekend coding workshops for high-school students in Alexandria. No teaching experience required — just patience and a willingness to explain the same concept three different ways.",
    deadline: "2026-09-10",
    postedAt: "2026-08-18",
    level: "any",
    applied: false,
  },
  {
    id: 106,
    title: "React Developer (Contract)",
    company: "Orion Retail Systems",
    companyLogo: "OR",
    type: "job",
    workMode: "remote",
    location: "Remote (Egypt)",
    skills: ["React", "TypeScript", "REST APIs"],
    description:
      "A 4-month contract building a point-of-sale dashboard for a regional retail chain. Fully remote, async-friendly team, clear scope, possibility of extension based on performance.",
    deadline: "2026-09-20",
    postedAt: "2026-08-14",
    level: "junior",
    applied: false,
  },
  {
    id: 107,
    title: "Software Engineering Internship",
    company: "Falcon Logistics",
    companyLogo: "FL",
    type: "internship",
    workMode: "hybrid",
    location: "6th of October City, Egypt",
    skills: ["JavaScript", "React", "Problem Solving"],
    description:
      "Falcon Logistics runs the routing software behind a regional delivery network. Interns work on real internal tools under the direct supervision of the engineering lead, with a strong track record of converting interns to full-time hires.",
    deadline: "2026-10-01",
    postedAt: "2026-08-22",
    level: "entry",
    applied: false,
  },
  {
    id: 108,
    title: "UI Engineer",
    company: "Meridian Studio",
    companyLogo: "MS",
    type: "job",
    workMode: "remote",
    location: "Remote (Worldwide)",
    skills: ["React", "CSS", "Design Systems", "Accessibility", "TypeScript", "Figma", "Responsive Design", "Animation"],
    description:
      "Meridian Studio is a small design-led product agency. We're hiring a UI engineer who genuinely cares about spacing, typography, and motion — someone who can turn a rough Figma file into production code without losing the design intent.",
    deadline: "2026-10-10",
    postedAt: "2026-08-11",
    level: "mid",
    applied: false,
  },
  {
    id: 109,
    title: "Junior Backend Developer",
    company: "Cedar Robotics",
    companyLogo: "CR",
    type: "job",
    workMode: "on-site",
    location: "Giza, Egypt",
    skills: ["Node.js", "Express", "SQL"],
    description:
      "A second, backend-focused opening on the same Cedar Robotics team as our full-stack role. You'll work primarily on the API layer that our robots' onboard software talks to.",
    deadline: "2026-10-05",
    postedAt: "2026-08-12",
    level: "junior",
    applied: false,
  },
  {
    id: 110,
    title: "Product Design Scholarship",
    company: "Meridian Studio",
    companyLogo: "MS",
    type: "scholarship",
    workMode: "remote",
    location: "Remote (MENA)",
    skills: ["Figma", "UX Research", "Prototyping"],
    description:
      "An 8-week remote scholarship for aspiring product designers, run by Meridian Studio's own design team, culminating in a portfolio review and potential internship offer.",
    deadline: "2026-09-28",
    postedAt: "2026-08-16",
    level: "entry",
    applied: false,
  },
  {
    id: 111,
    title: "Volunteer Curriculum Reviewer",
    company: "Nile Youth Foundation",
    companyLogo: "NY",
    type: "volunteer",
    workMode: "remote",
    location: "Remote (Egypt)",
    skills: ["React", "Technical Writing"],
    description:
      "Review and suggest improvements to our free beginner React curriculum, used by over 20 community centers across Egypt. A few hours a month, fully remote and asynchronous.",
    deadline: "2026-10-15",
    postedAt: "2026-08-19",
    level: "any",
    applied: false,
  },
  {
    id: 112,
    title: "Frontend Developer",
    company: "BrightPath Analytics",
    companyLogo: "BP",
    type: "job",
    workMode: "hybrid",
    location: "Cairo, Egypt",
    skills: ["React", "TypeScript", "Data Visualization", "REST APIs"],
    description:
      "BrightPath is hiring a full-time frontend developer to own our internal analytics dashboards end-to-end, working closely with our data science team to turn raw metrics into something genuinely readable.",
    deadline: "2026-10-08",
    postedAt: "2026-08-17",
    level: "mid",
    applied: false,
  },
  {
    id: 113,
    title: "Junior QA / Test Engineer",
    company: "Orion Retail Systems",
    companyLogo: "OR",
    type: "job",
    workMode: "on-site",
    location: "Nasr City, Cairo",
    skills: ["JavaScript", "Testing", "Attention to Detail"],
    description:
      "A junior QA role for someone who enjoys breaking things on purpose. You'll test our point-of-sale dashboard across devices and write up clear, reproducible bug reports for the engineering team.",
    deadline: "2026-09-22",
    postedAt: "2026-08-13",
    level: "entry",
    applied: false,
  },
  {
    id: 114,
    title: "Data Engineering Internship",
    company: "Delta Health Solutions",
    companyLogo: "DH",
    type: "internship",
    workMode: "hybrid",
    location: "Cairo, Egypt",
    skills: ["SQL", "Python", "Data Pipelines"],
    description:
      "Work alongside our data engineering team building pipelines that clean and structure anonymized healthcare data. A great fit for someone considering a data-focused path after this program.",
    deadline: "2026-09-18",
    postedAt: "2026-08-21",
    level: "entry",
    applied: false,
  },
  {
    id: 115,
    title: "React Native Developer",
    company: "Falcon Logistics",
    companyLogo: "FL",
    type: "job",
    workMode: "remote",
    location: "Remote (Egypt)",
    skills: ["React Native", "TypeScript", "Mobile UI"],
    description:
      "Falcon Logistics is extending its internal delivery-tracking tools into a driver-facing mobile app. Looking for someone with solid React fundamentals who's excited to pick up React Native specifically.",
    deadline: "2026-10-12",
    postedAt: "2026-08-23",
    level: "mid",
    applied: false,
  },
  {
    id: 116,
    title: "Scholarship: Women in Tech Fellowship",
    company: "Nile Youth Foundation",
    companyLogo: "NY",
    type: "scholarship",
    workMode: "hybrid",
    location: "Cairo, Egypt",
    skills: ["Any Technical Background"],
    description:
      "A 3-month fellowship for women pursuing their first technical role, including mentorship from working engineers, a stipend, and a closing showcase event with hiring partners.",
    deadline: "2026-09-27",
    postedAt: "2026-08-09",
    level: "any",
    applied: false,
  },
  {
    id: 117,
    title: "Junior Full-Stack Developer",
    company: "NovaWorks",
    companyLogo: "NW",
    type: "job",
    workMode: "hybrid",
    location: "Cairo, Egypt",
    skills: ["React", "Node.js", "TypeScript", "MongoDB"],
    description:
      "A second junior opening at NovaWorks, this one split between our React frontend and our Node/Express API layer. Ideal if you enjoyed both halves of this course roughly equally.",
    deadline: "2026-10-02",
    postedAt: "2026-08-24",
    level: "junior",
    applied: false,
  },
  {
    id: 118,
    title: "Technical Documentation Volunteer",
    company: "Meridian Studio",
    companyLogo: "MS",
    type: "volunteer",
    workMode: "remote",
    location: "Remote (Worldwide)",
    skills: ["Technical Writing", "React"],
    description:
      "Help document Meridian's internal component library so future junior hires ramp up faster. Light, flexible commitment — ideal alongside a full-time job search.",
    deadline: "2026-10-20",
    postedAt: "2026-08-25",
    level: "any",
    applied: false,
  },
  {
    id: 119,
    title: "Support Engineer (Junior)",
    company: "Orion Retail Systems",
    companyLogo: "OR",
    type: "job",
    workMode: "hybrid",
    location: "Cairo, Egypt",
    skills: ["JavaScript", "Customer Communication", "Debugging"],
    description:
      "A junior support engineering role investigating and triaging bug reports from real retail customers before escalating to the core engineering team — excellent exposure to a production codebase early in your career.",
    deadline: "2026-09-24",
    postedAt: "2026-08-08",
    level: "entry",
    applied: false,
  },
  {
    id: 120,
    title: "Backend Internship",
    company: "BrightPath Analytics",
    companyLogo: "BP",
    type: "internship",
    workMode: "on-site",
    location: "Cairo, Egypt",
    skills: ["Node.js", "Express", "SQL"],
    description:
      "A 3-month internship on BrightPath's backend team, building and documenting new endpoints for our analytics platform under the guidance of a senior engineer.",
    deadline: "2026-09-16",
    postedAt: "2026-08-26",
    level: "entry",
    applied: false,
  },
];
